version: '3'

services:
  nginx:
    image : nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
      - ./certs:/etc/nginx/certs 
    networks:
      - my-network
    depends_on:
      - web

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  web:
    image: python:3.12-slim  # Use a base Python image
    command: >
      sh -c "pip install -r /app/requirements.txt &&
              python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: django_db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
