# Generated by Django 5.0.3 on 2024-03-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0002_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
