# Generated by Django 5.0.3 on 2024-03-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0003_alter_certificates_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='name',
        ),
    ]
