# Generated by Django 5.0.3 on 2024-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0004_remove_certificates_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='source_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
