# Generated by Django 5.0.3 on 2024-10-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0005_certificates_description_certificates_source_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='profile_image',
        ),
    ]
